"""Python SDK for the API Baseball REST API.

Example::

    from apibaseball import BaseballClient

    client = BaseballClient(api_key="your-api-key")
    countries = client.get_countries()
"""

from ._http import (
    DEFAULT_BASE_URL,
    AuthIn,
    HttpRequest,
    HttpResponse,
    Transport,
    urllib_transport,
)
from ._version import __version__
from .client import (
    BaseballClient,
    BaseballClientConfig,
    GetGamesParams,
    GetLeaguesParams,
    GetOddsParams,
    GetPlayersParams,
)
from .errors import BaseballApiError
from .types import (
    ApiResponse,
    BaseballGame,
    BaseballGameLeague,
    BaseballGameScore,
    BaseballGameScoreMap,
    BaseballGameTeam,
    BaseballGameTournament,
    BaseballGameVenue,
    BaseballLiveGame,
    BaseballLiveLeagueGroup,
    BaseballLiveTeam,
    BaseballLiveVenue,
    BaseballOdds,
    BaseballOddsMarket,
    BaseballOddsOutcome,
    BaseballOddsPrice,
    BaseballPlayer,
    BaseballPlayerStats,
    BaseballPlayerStatsBase,
    BaseballPlayerStatsBatting,
    BaseballPlayerStatsFielding,
    BaseballPlayerStatsPitching,
    BaseballStanding,
    BaseballStandings,
    BaseballStandingsLeague,
    BaseballTeamInjury,
    BaseballTeamStats,
    BaseballTeamStatsBatting,
    BaseballTeamStatsFielding,
    BaseballTeamStatsPitching,
    Country,
    League,
    Paginated,
    Pagination,
    Player,
    Team,
    Venue,
)

__all__ = [
    "DEFAULT_BASE_URL",
    "ApiResponse",
    "AuthIn",
    "BaseballApiError",
    "BaseballClient",
    "BaseballClientConfig",
    "BaseballGame",
    "BaseballGameLeague",
    "BaseballGameScore",
    "BaseballGameScoreMap",
    "BaseballGameTeam",
    "BaseballGameTournament",
    "BaseballGameVenue",
    "BaseballLiveGame",
    "BaseballLiveLeagueGroup",
    "BaseballLiveTeam",
    "BaseballLiveVenue",
    "BaseballOdds",
    "BaseballOddsMarket",
    "BaseballOddsOutcome",
    "BaseballOddsPrice",
    "BaseballPlayer",
    "BaseballPlayerStats",
    "BaseballPlayerStatsBase",
    "BaseballPlayerStatsBatting",
    "BaseballPlayerStatsFielding",
    "BaseballPlayerStatsPitching",
    "BaseballStanding",
    "BaseballStandings",
    "BaseballStandingsLeague",
    "BaseballTeamInjury",
    "BaseballTeamStats",
    "BaseballTeamStatsBatting",
    "BaseballTeamStatsFielding",
    "BaseballTeamStatsPitching",
    "Country",
    "GetGamesParams",
    "GetLeaguesParams",
    "GetOddsParams",
    "GetPlayersParams",
    "HttpRequest",
    "HttpResponse",
    "League",
    "Paginated",
    "Pagination",
    "Player",
    "Team",
    "Transport",
    "Venue",
    "__version__",
    "urllib_transport",
]
